[package]
name = "http2hpack"
version = "0.1.0"
authors = ["Chris Jones"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["http2", "hpack", "huffman", "tls", "http"]
repository = "https://github.com/lambdastackio/http2hpack"
homepage = "https://lambdastackio.github.io/http2hpack/http2hpack"
documentation = "https://lambdastackio.github.io/http2hpack/http2hpack"
description = """
HTTP/2 and HPACK library to be used in client and server. All of the multiplexing is based on the tokio project.
"""

[dependencies]
url = "1"
term = "0.4"
clap = "2"
env_logger = "0.3"
lsio = "0.1"
rustc-serialize = "0.3"
#tokio-tls = "0"
